#!/usr/bin/env python

from dungeoneer import *
import sys

if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        print "usage: %s PATH [PATH ...]" % sys.argv[0]
        sys.exit(1)

    for path in args:
        with open(path, 'r') as f:
            print Parser(TestBuilder()).parsefile(f)
